### ISSUE TITLE
Tranmission-Remote-GTK dev says he would welcome you to help add Flatpak support to original project

### ISSUE THREAD

**Issue by Pentaphon** [flathub/io.github.TransmissionRemoteGtk#4]
So I asked the dev about adding your Flatpak to his readme and he responded:

>That flatpak is not part of this project. I don't know who makes it, but if they want to come here and ask to have it added or even add support to this repo for building a flatpak they'd be more than welcome.

https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/183

I think it would be a benefit to the project as a whole if you guys worked together to make everything official. Please consider doing so.

**Comment by hfiguiere** [comment]
what do you want me to do?

**Comment by hfiguiere** [comment]
I pinged @TingPing back then,

**Comment by Pentaphon** [comment]
> what do you want me to do?

Contact Lasereyess from that thread I linked. He said he would help make your Flatpak an official part of the project. The Flathhub.org admins can help you transfer anything you need to transfer because they encourage Flatpaks on Flathub to come directly from the original author, so if you guys can work together to integrate the existing Flatpak into the original project, that would be great for everybody. 

https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do

Thanks for responding to my request. I hope you guys work together to make the Flatpak an official part of the transmission-remote-gtk project.

**Comment by hfiguiere** [comment]
And the original submission https://github.com/flathub/flathub/pull/2539 mentionned I contacted someone as well. 

As for working together, I already did https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/180

(and yes I already pushed 1.5.1 today)

**Comment by Pentaphon** [comment]
Thanks! I'm glad you guys are now in contact. I really appreciate your responsive Flatpak and the author's project.

**Comment by TingPing** [comment]
I added @LaserEyess to the repo. @hfiguiere has been doing a good job maintaining this so I don't think anything needs to change other than the formality that upstream can do updates or fixes when needed. (They already could since I was involved with upstream somewhat of course)
